project_id = "rpuxoxvjhxnsdkgypsfm"

[functions.create-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.import-users]
verify_jwt = true

[functions.update-user-role]
verify_jwt = true

[functions.get-users-auth-info]
verify_jwt = false
